// <auto-generated />
using System;
using Hems.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hems.Api.Data.Migrations
{
    [DbContext(typeof(HemsDbContext))]
    partial class HemsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Hems.Api.Models.AutomationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AutomationLogs");
                });

            modelBuilder.Entity("Hems.Api.Models.EnergyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryChargePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("ConsumptionWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("GridFeedInWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("ProductionWatts")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("EnergyReadings");
                });

            modelBuilder.Entity("Hems.Api.Models.SpotPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerKwh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc", "Area");

                    b.ToTable("SpotPrices");
                });

            modelBuilder.Entity("Hems.Api.Models.WeatherForecastEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CloudCoverPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ForecastTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SolarRadiationWm2")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ForecastTime");

                    b.ToTable("WeatherForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
